services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel-hub-1
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - /root/docker/beszel-hub/beszel_data:/beszel_data
  # cloudflared:
  #   container_name: cloudflared-beszel-hub
  #   image: cloudflare/cloudflared
  #   restart: unless-stopped
  #   command: tunnel run
  #   environment:
  #     - TUNNEL_TOKEN=
